import json

with open("excersizes.json", "r") as file:
    exercises = json.load(file)

print(len(exercises.keys()))

exc_names = ['Ab rollouts',
 'Arm over arm',
 'Arnold press',
 'Atlas stones',
 'Axle RDL',
 'Axle bar OHP',
 'Axle bar back squats',
 'Axle clean and press',
 'Back extensions',
 'Back squat',
 'Bamboo bar back squat',
 'Bamboo bar bench',
 'Band pull apart',
 'Band pull aparts',
 'Band pull aparts ',
 'Banded monster walks',
 'Barbell Bench press',
 'Barbell Bulgarians',
 'Barbell Good Mornings',
 'Barbell Hip thrusts',
 'Barbell Rdl',
 'Barbell back squat',
 'Barbell back squat ',
 'Barbell back squats',
 'Barbell bench',
 'Barbell bench press',
 'Barbell bent rows',
 'Barbell deadlifts',
 'Barbell flat bench',
 'Barbell flat bench press',
 'Barbell front raises ',
 'Barbell front squat',
 'Barbell push press',
 'Barbell rdl',
 'Barbell shoulder press',
 'Barbell squat',
 'Barbell squats',
 'Barbell strict press',
 'Bb Bench press',
 'Bb Deadlift',
 'Bb Rdls',
 'Bb Shoulder press',
 'Bb back squat',
 'Bb back squats',
 'Bb back squats ',
 'Bb back squats (paused)',
 'Bb bench press',
 'Bb bent rows',
 'Bb deadlift',
 'Bb flat Bench press',
 'Bb front squat',
 'Bb hip thrust ',
 'Bb hip thrusts',
 'Bb rdl',
 'Bb rows',
 'Bb seated OHP',
 'Bb seated OHP ',
 'Bb vent rows',
 'Bench',
 'Bench Press',
 'Bench press',
 'Bench press (no leg drive)',
 'Bend barbell rows',
 'Bent Barbell rows',
 'Bent Lat rows',
 'Bent bar rows',
 'Bent barbell rows',
 'Bent bb row',
 'Bent bb rows',
 'Bent rows',
 'Bicep curl smart machine',
 'Bicep curls',
 'Block pulls',
 'Bulgarian split squats',
 'Bulgarians',
 'Cable Face pulls',
 'Cable Lat Pull Down',
 'Cable Lat pull down',
 'Cable Lat pull downs',
 'Cable Lateral raises',
 'Cable chest flys',
 'Cable face pulls',
 'Cable flys low to high',
 'Cable front raises',
 'Cable lat pulldown',
 'Cable lateral raises',
 'Cable pull downs',
 'Cable pulldowns',
 'Cable rope curls',
 'Cable rows',
 'Cable tricep extensions',
 'Calf raises ',
 'Car tire axle deadlift',
 'Car tire deadlift',
 'Car tire deadlift ',
 'Chest flys',
 'Chest supported Db front raises',
 'Chest supported db rear delt raises',
 'Circus Dumbbell',
 'Clean and jerk ',
 'Close grip Lat pull downs',
 'Close grip Lat pull-down',
 'Close grip barbell bench',
 'Close grip bench',
 'Close grip bench ',
 'Close grip cable pull downs',
 'Close grip incline press',
 'Close grip neutral grip press',
 'Close grip pull downs',
 'Close grip push up',
 'Close grip push-ups',
 'Close grip push-ups ',
 'Close grip pushups',
 'Concentration curls',
 'Crunches',
 'D handle Lat pull downs',
 'Db Farmers carry',
 'Db Lat raises',
 'Db curls',
 'Db front raises',
 'Db hammer curls',
 'Db incline press',
 'Db lunges',
 'Db over head press',
 'Db shrug',
 'Dead hang ',
 'Deadhang',
 'Deadhangs',
 'Deadlift',
 'Deadlifts',
 'Deadlifts (paused)',
 'Dead’s',
 'Dear delt cable flys',
 'Decline bench press',
 'Deficit Deadlift (4 inch)',
 'Deficit conventional deadlifts',
 'Delt raises (front Lat upright)',
 'Dinny',
 'Dinny lift',
 'Dips',
 'Dumbbell Front raises',
 'Dumbbell Lat Raises',
 'Dumbbell Lat raises',
 'Dumbbell Rear delt flys',
 'Dumbbell Romanian deadlifts',
 'Dumbbell bench press',
 'Dumbbell bicep curls',
 'Dumbbell chest flys',
 'Dumbbell chest supported rear delt raises',
 'Dumbbell flat chest flys',
 'Dumbbell front raises',
 'Dumbbell incline press',
 'Dumbbell lateral raise',
 'Dumbbell lateral raises',
 'Dumbbell rdls',
 'Dumbbell rear delt flys',
 'Dumbbell shoulder press',
 'Dumbell shoulder press',
 'Ez Barbell curls',
 'Ez bar bicep curls',
 'Ez bar curls',
 'Ez bar curls ',
 'Ez bar incline curls',
 'Ez bar incline skull crushers',
 'Ez bar skull crusher',
 'Ez bar skull crushers',
 'Ez bar standing curls',
 'Ez bar upright rows',
 'Face pulls',
 'Face pulls ',
 'Farmers',
 'Farmers Carry',
 'Farmers carry',
 'Fat grip hammer curls',
 'Floor barbell bench',
 'Floor press',
 'Flutter kicks',
 'French Press',
 'French press',
 'Front shoulder raise bb',
 'Front squat',
 'Front squats',
 'GHR',
 'Ghr',
 'Glute bridge',
 'Goblet squat',
 'Goblet squats',
 'Good mornings',
 'Hack squat',
 'Hammer curls',
 'Hammer hold',
 'Hamstring curls',
 'Hand up pushups',
 'Hanging Toes to Bar',
 'Hercules hold',
 'Hi to low cable crossovers',
 'High incline bb bench',
 'High incline bench',
 'High to low cable flys',
 'Hip Adductor machine',
 'Hip abductor machine',
 'Hip adductors ',
 'Hip thrust',
 'Hip thrust ',
 'Hip thrusts',
 'Hip thrusts ',
 'Hip thrusts (wagon wheel)',
 'Husafell',
 'Husafell stones',
 'Incline French press',
 'Incline French press ',
 'Incline bb bench',
 'Incline bench',
 'Incline bench press ',
 'Incline cable flys',
 'Incline chest supported db front raises',
 'Incline chest supported db lat raises',
 'Incline db bench',
 'Incline db bench press',
 'Incline dumbbell bench press',
 'Incline dumbbell bench press ',
 'Incline dumbbell press',
 'Incline dumbell',
 'Incline ezbar skull crusher',
 'Incline press',
 'Jpg Lat pull downs',
 'Kb goblet squats',
 'Kb swing',
 'Kb swings',
 'Keg press',
 'Keg throw for distance',
 'Keg toss',
 'Kettle bell swings',
 'Kettlebell Swings',
 'Kettlebell swings',
 'Kneeling Rollouts',
 'Landmine press',
 'Lat pull down',
 'Lat pull downs',
 'Lat pull-down',
 'Lat raises',
 'Lat raises ',
 'Lateral delt raises',
 'Leg curls',
 'Leg curls smart machine',
 'Leg extensions',
 'Leg extensions ',
 'Leg extensions smart machine',
 'Leg press',
 'Leg raises',
 'Log press',
 'Log push press',
 'Low to high cable chest flys',
 'Low to high cable crossovers',
 'Low to high cable flys',
 'Lunges',
 'Lying Hamstring curls',
 'Lying leg curl',
 'Lying machine leg curls',
 'Machine Lat pull downs',
 'Machine chest flys',
 'Machine chest press',
 'Machine hip abductor',
 'Machine hip adductor',
 'Machine hip thrusts ',
 'Machine leg press',
 'Machine rear delt flys',
 'Machine reverse flys',
 'Machine rows',
 'Machine shoulder press',
 'Machine shoulder press ',
 'Machine tricep extension',
 'OH Barbell Press',
 'Odd object carry',
 'Oh bb tricep extension ',
 'Overhead cable extensions',
 'Paused Incline bench press',
 'Paused deadlifts ',
 'Pec dec flys ',
 'Pec deck',
 'Pec deck chest flys',
 'Pec deck rear delt flys',
 'Pendlay rows',
 'Plank',
 'Plank ',
 'Pull ups',
 'Pull ups ',
 'Pull-ups',
 'Pullups',
 'Push press',
 'Quad extensions',
 'Rack pulls',
 'Rdl',
 'Rdls',
 'Rdls ',
 'Rear delt fly',
 'Rear delt flys',
 'Rear delt raises bb',
 'Reverse ez bar curls',
 'Reverse hypers',
 'Reverse lunges',
 'Rope Tricep push downs',
 'Rope climb pulls',
 'Rope extensions',
 'Rope face pulls',
 'Rope push downs',
 'Rope push downs ',
 'Rope rows',
 'Rope tricep extensions',
 'SA cable rows',
 'Sally push-ups',
 'Sand bag throws ',
 'Sand bag toss',
 'Sand bags',
 'Sand bags over bar',
 'Sandbag carry',
 'Sandbag press',
 'Sandbag runs',
 'Sandbag throws',
 'Sandbag throws ',
 'Sandbag to shoulder',
 'Sandbag to shoulder ',
 'Sandbag toss',
 'Sandbag toss ',
 'Sandbags',
 'Sandbags to shoulder',
 'Sbb box squats',
 'Seated Barbell strict press',
 'Seated Hamstring curls',
 'Seated Leg curls',
 'Seated Leg extensions',
 'Seated OHP Dumbbell',
 'Seated OHP: ',
 'Seated Quad extensions',
 'Seated barbell OHP',
 'Seated cable rows',
 'Seated hamstring curls',
 'Seated leg curls',
 'Seated row',
 'Seated row smart machine',
 'Shoulder 3 ways',
 'Shoulder press',
 'Shoulder press smart machine',
 'Shrug',
 'Shrugs',
 'Side bends',
 'Side raises ',
 'Single Leg press',
 'Single are sumo deadlift',
 'Single arm Overhead tricep extensions',
 'Single arm dumbbell bent rows',
 'Single arm dumbbell extensions',
 'Single arm dumbbell overhead tricep extensions',
 'Single arm dumbbell overhead tricep press',
 'Single arm dumbbell tricep extensions',
 'Single arm overhead cable extensions',
 'Single arm tricep extensions',
 'Single leg squats',
 'Skullcrushers',
 'Sled pull',
 'Sled push',
 'Smart chest press machine',
 'Smart machine seated row',
 'Smart machine shoulder press',
 'Smart machine tricep press',
 'Smart row machine',
 'Smart shoulder press',
 'Smart tricep push down ',
 'Smith machine RDL',
 'Smith machine back squat',
 'Smith machine hip thrust ',
 'Snatch Grip Deadlift',
 'Snatch grip Block pulls',
 'Snatch grip block pulls',
 'Snatch grip deadlifts',
 'Snatch grip rack pulls',
 'Squats',
 'Standing French press',
 'Standing French press ',
 'Standing OHP',
 'Standing machine calf raises',
 'Stone loads',
 'Stone over bar',
 'Stone to shoulder',
 'Stones',
 'Stones to Platform',
 'Stones to platform',
 'Straight arm cable pull downs',
 'Straight arm pull downs',
 'Strict barbell',
 'Strict barbell press',
 'Strict log press',
 'Strict press',
 'Strict shoulder press',
 'Sumo deadlift',
 'T bar rows',
 'T-bar rows',
 'Tire flips',
 'Tireflip',
 'Trap bar deadlift',
 'Trap bar deadlifts',
 'Trap bar jumps',
 'Tricep cable extensions',
 'Tricep cable push downs',
 'Tricep extensions',
 'Tricep press downs',
 'Tricep press smart machine',
 'Tricep push downs',
 'Tricep push downs ',
 'Tricep rope push down',
 'Truck pull',
 'Truck tire deadlift',
 'Upper back rows',
 'Upright rows',
 'Viking press',
 'Walking lunges',
 'Wheelbarrow push',
 'Wheelbarrow runs',
 'Wide grip Cable row',
 'Yoke',
 'Z press']